### ISSUE TITLE
409 Conflict or 412 Precondition Failed

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#1]
https://github.com/garethsb/nmos-rwnode/blob/5e0fd19ec0ec9d38e30bc1f988b05af33a4350f1/APIs/ReadWriteNodeAPI.raml#L57-L58

[`412` Precondition Failed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412) is normally used with `ETag`

**Comment by cristian-recoseanu** [comment]
Discussion during the meeting: This has impacts on the version check mechanism.

The group currently doesn't feel there is a specific use case that needs addressing with this mechanism and it also introduces a concept which doesn't exist in the other specifications.

The notification mechanism provides a way for systems to stay in sync with the recent changes and re-try.

**Comment by peterbrightwell** [comment]
See decision on #8. Closing.
