### ISSUE TITLE
State that tag keys need to be unique

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/is-13#10]
Discussion 2023-05-04: We would benefit from text stating that the tag keys need to be unique.  They are currently URNs but there's nothing in theory stopping us having duplicates.

**Comment by garethsb** [comment]
See [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259#section-4) The JavaScript Object Notation (JSON) Data Interchange Format:

> The names within an object SHOULD be unique.
...
> An object whose names are all unique is interoperable in the sense
   that all software implementations receiving that object will agree on
   the name-value mappings.  When the names within an object are not
   unique, the behavior of software that receives such an object is
   unpredictable.

**Comment by garethsb** [comment]
IMHO, this is really something for NMOS generally, e.g. maybe in https://specs.amwa.tv/is-04/releases/v1.3.2/docs/APIs.html.

**Comment by garethsb** [comment]
Would be resolved by https://github.com/AMWA-TV/is-04/pull/198
