### ISSUE TITLE
Bulk changes

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#2]
Do we need a bulk API?

Making changes for many resources of one type could be done by supporting `PATCH` (or `POST`) on the collection endpoints _/devices_, _/sources_, etc. with an array of objects - each object would need `id` property in addition to the current _resource_core_patch.json_ properties.

Obvs, could also come up with a single request endpoint to do resources of several types.

These approaches would still need an object per resource. If we want a way to have one change applied to multiple resources, that needs a different kind of API.

**Comment by cristian-recoseanu** [comment]
Discussion during the meeting: the group feels this will complicate the API and put more burden on the nodes/devices which can instead be better placed in the provisioning tool / controller.

**Comment by peterbrightwell** [comment]
Decision 2023-05-04: no bulk API support this iteration. Closing.
