### ISSUE TITLE
Relative merits of Node-based vs Registry-based Annotation API

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#28]
We've discussed on group calls, the relative merits of Node-based vs Registry-based Annotation API.

Some of the things we thought of...

| | Node-based | Registry-based |
|-|-|-|
| Discovery mechanism | Node `services` | Not clear... DNS-SD? |
| Interop with Node API | Well defined | Not provided |
| Interop with Query API | Well defined | Provided but complicated a little by `version` |
| Annotation limits | Requirements based on low-powered devices | Could be relaxed? |
| Annotation lifetime | Well defined | Probably needs configurable garbage collection? |
| Annotation mobility | Intrinsic | No |

**Comment by jmailhot** [comment]
from a purist standpoint, i dislike the endpoints being responsible for "storing state" of things that they have no active part in.  but registry-based annotations also brings some complication -- at the moment, everything in the NMOS registry is a copy of data whose definitive source is elsewhere.  so if we start using the registry to also hold annotations, we'll need to decide if its the definitive source (and responsible for persistence) of those annotations, or if the party that makes the annotation is also responsible for pushing/maintaining it in the registry the same way that nodes are responsible for maintaining their registrations today.  Neither option is perfect.  There is especially a funny issue if the node drops out and comes back, the registry might purge the node's information - when the node comes back, would the registry "remember" the previous annotations, or would the annotations manager need to put them back once it sees the node re-appear?

**Comment by peterbrightwell** [comment]
Update 2023-07-13: not all use cases have a registry so the above questions would need be considered.  However this is outside current agreed iteration scope.

**Comment by timhall99** [comment]
Closed as the group has agreed the IS-13 v1.0 node-based approach - could be reopened at a later date, if necessary.
