### ISSUE TITLE
Join the dots on updating the Registry after updating annotations

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#29]
The **Version Increments** section talks about keeping the properties in sync with the Node API and specifically the `version` attribute. It could probably do with an explicit link to https://specs.amwa.tv/is-04/releases/v1.3.2/docs/APIs_-_Common_Keys.html#version and an informative note highlighting that this means in registered operation, the changes are registered with the Registration API and thus Controllers can receive notifications of the changes via Query API WebSocket subscriptions.

**Comment by peterbrightwell** [comment]
Update 2023-07-13: those on the call either agreed or didn't disagree so yes dots should be joined.
