### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#3]
Can we define a minimum level of support for changing label, description and tags?

E.g.
* whether the spec requires all of these _are_ editable
* whether there is a guaranteed minimum supported string length
* whether there is a guaranteed minimum number of tags that can be added, and values per tag

And then just accept that `500` responses may occur if these are exceeded...

_Or_

Do we need some kind of _/constraints_ endpoint that allows each Node to indicate its supported string lengths, maximum number of tags and tag values, and which tags are editable, etc.

**Comment by garethsb** [comment]
One mitigation for not describing via an API which tags are editable would be for the spec to define a namespace such as `urn:x-nmos:tag:user:` that was required to be read/write (still subject to other kinds of limitations mentioned of course) whereas other namespaces like `urn:x-manufacturer:tag:` would be defined by the namespace owner (`urn:x-nmos:tag:asset:` for example would be defined as read-only).

**Comment by cristian-recoseanu** [comment]
Discussion during the meeting: The group feels that adding a separate /contraints endpoint will greatly complicate the API.

Define a guaranteed minimum supported string length for labels which a device can accept in the request.

The rest of the limitations should be reflected using HTTP error codes and some descriptive error messages.

The group feels that tags entered/modified/removed through this API should all live in the `urn:x-nmos:tag:user:` namespace which would make it clearer and simplify the `null` behaviour with respect to tags (as now you would only be able to remove tags).

**Comment by garethsb** [comment]
> The group feels that tags entered/modified/removed through this API should all live in the urn:x-nmos:tag:user: namespace

I think some vendors would like to allow their tags to be updated via this API, which is why I propose that the spec define the `user` namespace as read/write but not prohibit use with other namespaces.

**Comment by peterbrightwell** [comment]
> I think some vendors would like to allow their tags to be updated via this API, which is why I propose that the spec define the user namespace as read/write but not prohibit use with other namespaces.

That seems reasonable to me, and not preventing use with other namespaces keeps us within our current scope of work?

**Comment by garethsb** [comment]
> And then just accept that 500 responses may occur if these are exceeded...

Another alternative... allow partial success (as mentioned by Cristian in #6), e.g. applying changes to tags but not applying an over-long description, or truncating such an over-long value. I'm not convinced this is a good idea.

**Comment by peterbrightwell** [comment]
Discussion 2023-05-04: possible ambiguity between equivalent user and vendor tags? Separate namespaces would help here. Example of `location` which could be provided via manufacturer API/GUI or via this API.  

Decision: Provide a `urn:x-nmos:tag:user:` namespace, which is guaranteed to be read-write (subject to internal device limitations e.g. memory). Outside that namespace not guaranteed to be writable.

**Comment by peterbrightwell** [comment]
Will be sorted by #16
