### ISSUE TITLE
How to handle external changes

### ISSUE THREAD

**Issue by VenkateswaranJ** [AMWA-TV/is-13#30]
If the label, description & tags are changed via some external mechanism then updating the `Version Timestamp` is enough?

**Comment by garethsb** [comment]
Yes, I think you're right. This spec says "The [Core Resource Properties](https://github.com/AMWA-TV/is-13/blob/v1.0-dev/docs/Overview.md#core-resource-properties) of the resources under the Annotation API `/node/` path MUST also match the corresponding IS-04 properties." And IS-04 describes that the `version` is updated whenever any other properties are.

**Comment by timhall99** [comment]
Closed - answered by Gareth
