### ISSUE TITLE
Add Overview and other common specification sections

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#4]
Needs doing :-)

**Comment by garethsb** [comment]
## Data Model

Refer to shared model with IS-04. Mention the six resource types.

Describe that all these core resources have the same properties. Refer to IS-04 APIs - Common keys doc. (Incidentally no reason that doc doesn't have a section for `id` as far as I can see!)

## APIs

### Cross-Origin Resource Sharing (CORS)

### API Validation

### URLs: Approach to Trailing Slashes

### Error Codes & Responses

Etc. All v. similar to IS-04 or IS-05. Actually, IS-11 may be a good model to follow.

**Comment by peterbrightwell** [comment]
Will be sorted by https://github.com/AMWA-TV/is-13/pull/16
