### ISSUE TITLE
Addition or removal of specific tag values

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#5]
Currently API allows a tag to be removed or for the array of values to be replaced.
It does not provide a way to append a tag value or remove one or more values from the existing list.

**Comment by garethsb** [comment]
The proposed support for passing `version` as a precondition mechanism allows a Controller to avoid "mid-air edit collisions", so I'm not convinced there is sufficient motivation to support this feature.

**Comment by cristian-recoseanu** [comment]
Discussion during the meeting: The group is okay with the current approach:
`Currently API allows a tag to be removed or for the array of values to be replaced.`

**Comment by peterbrightwell** [comment]
Decision 2023-05-04: we are ok with the approach so closing.
