### ISSUE TITLE
Changes in this API MUST trigger IS-04 version changes

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/is-13#7]
which can be followed through the notification mechanism of a registry.

**Comment by garethsb** [comment]
Needs a prefix but can then be stronger:

When used with Node API, **_all_** properties in this API MUST be consistent with the Node API!

**Comment by peterbrightwell** [comment]
Decision 2023-05-04: we agree with @garethsb's proposal above (and IS-04 says this will set the version)
