### ISSUE TITLE
Decide whether to remove the version check mechanism

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/is-13#8]
The group currently doesn't feel there is a specific use case that needs addressing with this mechanism and it also introduces a concept which doesn't exist in the other specifications.

The notification mechanism provides a way for systems to stay in sync with the recent changes and re-try.

_Originally posted by @cristian-recoseanu in https://github.com/AMWA-TV/nmos-rwnode/issues/1#issuecomment-1525910933_

**Comment by garethsb** [comment]
This would just mean removing `version` (and if the group decide a bulk API isn't required, also the `id`) from the _resource_core_patch.json_ schema and related references in the `400` and `409` responses to `PATCH` in the RAML.

(I assume no-one would want to permit `id` and `version` to be included but ignore them.)

**Comment by peterbrightwell** [comment]
Decision 2023-05-04: remove `id` and `version` as discussed. Can also close #1.
